### PR TITLE
Added the ability to unfollow all followers.

### PR DESCRIPTION
**Pull request by kyranb**
added the method my_bot.auto_unfollow_all_followers() (ignores those in
your do not unfollow list)

### CODE REVIEW

**Comment by rhiever** [comment]
Hmm... this one seems a little superfluous, right? The same functionality could technically be replicated by having no users in the "keep following" list.

**Comment by kyranb** [comment]
No, as the only other method is ```unfollow_all_nonfollowers``` which checks whether they are following you back. This method will essentially remove all of the accounts you follow, except a few that you would always like to remain there.

**Comment by rhiever** [comment]
Ahhh, I overlooked that. Can you also please change the README to describe this new functionality?

**Comment by kyranb** [comment]
:+1: :smile:

**Comment by rhiever** [comment]
:+1:  TY!

**Pull request merged**
